/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 17:59:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import uta.mav.appoint.TimeSlotComponent;
import uta.mav.appoint.PrimitiveTimeSlot;
import uta.mav.appoint.CompositeTimeSlot;
import uta.mav.appoint.beans.AdvisingSchedule;
import uta.mav.appoint.beans.Appointment;

public final class advising_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (String) request.getAttribute("includeHeader"), out, false);
      out.write('\r');
      out.write('\n');
 ArrayList<String> array = (ArrayList<String>)session.getAttribute("advisors");
	if (array != null){ 
      out.write("\t    \t\t\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"page-header\">\r\n");
      out.write("\t\t<div class=\"pull-right form-inline\">\r\n");
      out.write("\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t \t<form action=\"advising\" method=\"post\" name=\"advisor_form\">\r\n");
      out.write("\t\t\t\t \t<input type=hidden name=advisor_button id=\"advisor_button\">\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\t<!-- begin processing advisors  -->\r\n");
      out.write("\t\t    \t\t\t\t<button type=\"button\" id=\"all1\" onclick=\"alladvisors()\">All</button>\r\n");
      out.write("\t\t    \t\t\t\t<script> function alladvisors(){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"advisor_button\").value = \"all\";\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tadvisor_form.submit();\r\n");
      out.write("\t\t    \t\t\t\t\t\t }\r\n");
      out.write("\t\t    \t\t\t\t</script>\r\n");
      out.write("\t\t    \t\t\t");
	for (int i=0;i<array.size();i++){ 
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t<button type=\"button\" id=\"button1");
      out.print(i);
      out.write("\" onclick=\"button");
      out.print(i);
      out.write("()\">");
      out.print(array.get(i));
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script> function button");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"advisor_button\").value = \"");
      out.print(array.get(i));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tadvisor_form.submit();\r\n");
      out.write("\t\t\t\t\t\t\t\t}</script>\r\n");
      out.write("\t\t\t\t\t\t");
	}
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
} 
		 else{
      out.write("\r\n");
      out.write("\t\t    <label><font color=\"#e67e22\" size=\"5\"> Log in to see Advisor schedules. </label>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t <!-- end processing advisors -->\t \r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"date-display span12\">\r\n");
      out.write("\t\t<h3></h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div id='calendar'></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--  begin processing schedules -->\r\n");
      out.write("\t\t");
 ArrayList<TimeSlotComponent> schedules = (ArrayList<TimeSlotComponent>)session.getAttribute("schedules");
		   ArrayList<Appointment> appointments = (ArrayList<Appointment>)session.getAttribute("appointments");
		    				
      out.write("<script>\r\n");
      out.write("\t\t    \t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t    \t\t\t\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t    \t\t\t\t\t\theader: {\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tleft:'month,basicWeek,basicDay',\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tright: 'today, prev,next',\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tcenter: 'title'\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdisplayEventEnd : {\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tmonth: true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tbasicWeek: true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t'default' : true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t\t\t\t");
if (schedules != null){
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t    \t,\r\n");
      out.write("\t\t    \t\t\t\t\t\teventClick: function(event,element){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tif (event.id >= 0){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"id1\").value = event.id;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"pname\").value = event.title;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\taddAppt.submit();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t\tupdateAppt.submit();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\tevents: [\r\n");
      out.write("\t\t \t\t    \t\t");
 int i = 0;
									for (i=0;i<schedules.size();i++){
      out.write(" \r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\ttitle:'");
      out.print(schedules.get(i).getName());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tstart:'");
      out.print(schedules.get(i).getDate()+"T"+schedules.get(i).getStartTime());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tend:'");
      out.print(schedules.get(i).getDate()+"T"+schedules.get(i).getEndTime());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tid:");
      out.print(i);
      out.write(",\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tbackgroundColor: 'blue'\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t");
if(i != (schedules.size()-1)||appointments != null){
      out.write(',');
}
      out.write("\r\n");
      out.write("\t\t \t\t\t\t\t \t\t");
}	
									if (appointments != null){
										for(i=1;i<1+appointments.size();i++){
      out.write("\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t{\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\ttitle:'");
      out.print(appointments.get(i-1).getAppointmentType());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tstart:'");
      out.print(appointments.get(i-1).getAdvisingDate()+"T"+appointments.get(i-1).getAdvisingStartTime());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tend:'");
      out.print(appointments.get(i-1).getAdvisingDate()+"T"+appointments.get(i-1).getAdvisingEndTime());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tid:");
      out.print(-i);
      out.write(",\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tbackgroundColor: 'orange'\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t");
if(i != appointments.size()){
      out.write(',');
}
 										}
									}
      out.write("\t\t \t\t\t\t\t \r\n");
      out.write("\t\t \t\t\t\t\t \t\t\t]");
}
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t});\r\n");
      out.write("\t\t    \t\t\t\t});\r\n");
      out.write("\t \t\t\t\t\t\t</script>\t\r\n");
      out.write("\t\t \t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t<form name=addAppt action=\"schedule\" method=\"get\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=id1 id=\"id1\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=pname id=\"pname\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=advisor_email id=\"advisor_email\">\r\n");
      out.write("\t</form>\t\t \t\t\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form name=updateAppt action=\"appointments\" method=\"get\">\r\n");
      out.write("\t</form>\r\n");
      out.write("  \t\r\n");
      out.write("\t<br/><br/><hr>\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
