/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 18:03:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import uta.mav.appoint.TimeSlotComponent;
import uta.mav.appoint.PrimitiveTimeSlot;
import uta.mav.appoint.CompositeTimeSlot;
import uta.mav.appoint.beans.AdvisingSchedule;
import uta.mav.appoint.beans.Appointment;
import java.util.ArrayList;

public final class allocate_005ftime_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (String) request.getAttribute("includeHeader"), out, false);
      out.write("\r\n");
      out.write("\t<div id='calendar'></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!--  begin processing schedules -->\r\n");
      out.write("\t\t");
 ArrayList<TimeSlotComponent> schedules = (ArrayList<TimeSlotComponent>)session.getAttribute("schedules");
		   ArrayList<Appointment> appointments = (ArrayList<Appointment>)session.getAttribute("appointments");
		    				
      out.write("<script>\r\n");
      out.write("\t\t    \t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t    \t\t\t\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t    \t\t\t\t\t\theader: {\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tleft:'month,basicWeek,basicDay',\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tright: 'today, prev,next',\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tcenter: 'title'\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdisplayEventEnd : {\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tmonth: true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tbasicWeek: true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t'default' : true,\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\teventMouseOver: function(event,jsEvent,view){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t$('.fc-event-inner', this).append('<div id=\\\"'+event.id+'\\\" class=\\\"hover-end\\\">'+$.fullCalendar.formatDate(event.end, 'h:mmt')+'</div>');\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\teventMouseout: function(event, jsEvent, view) {\r\n");
      out.write("\t\t    \t\t\t\t\t\t    $('#'+event.id).remove();\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdayClick: function(date,jsEvent,view){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"opendate\").value = date.format('YYYY-MM-DD');\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t$(\"#addTimeSlotModal\").modal();\r\n");
      out.write("\t\t    \t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t    \t\t\t");
if (schedules != null){
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t\t,\r\n");
      out.write("\t\t    \t\t\t\t\t\teventClick: function(event,element){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tif (event.id >= 0){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"StartTime2\").value = event.start.format('HH:mm');\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"EndTime2\").value = event.end.format('HH:mm');\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"pname\").value = event.title;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"Date\").value = event.start.format('YYYY-MM-DD');\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t$(\"#deleteTimeSlotModal\").modal();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t\tupdateAppt.submit();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\tevents: [\r\n");
      out.write("\t\t \t\t    \t\t");
 int i = 0;
									for (i=0;i<schedules.size();i++){
      out.write(" \r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\ttitle:'");
      out.print(schedules.get(i).getName());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tstart:'");
      out.print(schedules.get(i).getDate()+"T"+schedules.get(i).getStartTime());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tend:'");
      out.print(schedules.get(i).getDate()+"T"+schedules.get(i).getEndTime());
      out.write("',\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tid:");
      out.print(i);
      out.write(",\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\tbackgroundColor: 'blue'\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t");
if(i != (schedules.size()-1)||appointments != null){
      out.write(',');
}
      out.write("\r\n");
      out.write("\t\t \t\t\t\t\t \t\t");
}	
									if (appointments != null){
										for(i=1;i<appointments.size()+1;i++){ //start array at 1 to prevent 0 id -> appointment id's must be negative
      out.write(" \r\n");
      out.write("\t\t \t\t\t\t\t\t\t\t\t{\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\ttitle:'");
      out.print(appointments.get(i-1).getAppointmentType());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tstart:'");
      out.print(appointments.get(i-1).getAdvisingDate()+"T"+appointments.get(i-1).getAdvisingStartTime());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tend:'");
      out.print(appointments.get(i-1).getAdvisingDate()+"T"+appointments.get(i-1).getAdvisingEndTime());
      out.write("',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tid:");
      out.print(-i);
      out.write(",\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t\tbackgroundColor: 'orange'\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t\t");
if(i != (appointments.size()-1)){
      out.write(',');
}
 										}
									}
      out.write("\t\t \t\t\t\t\t \r\n");
      out.write("\t\t \t\t\t\t\t \t\t\t]");
}
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\t});\r\n");
      out.write("\t\t    \t\t\t\t});\r\n");
      out.write("\t \t\t\t\t\t\t</script>\t\r\n");
      out.write("\t\t \t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t<form name=addTimeSlot action=\"availability\" method=\"post\" onsubmit=\"return false;\">\r\n");
      out.write("\t<div class=\"modal fade\" id=\"addTimeSlotModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"addTimeSlotLabel\">Add Time Slots</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"starttime\">Start Time:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"time\" class=\"form-control\" name=starttime id=\"starttime\" step=\"300\">\r\n");
      out.write("\t\t \t\t\t\t<label for=\"tndtime\">End Time:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"time\" class=\"form-control\" name=endtime id=\"endtime\" step=\"300\">\r\n");
      out.write("\t\t \t\t\t\t<label for=\"opendate\">Date:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"text\" class=\"form-control\" name=opendate id=\"opendate\">\r\n");
      out.write("\t\t \t\t\t\t<label for=\"repeat\">Weekly repeat duration:</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=repeat id=\"repeat\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<label id=\"result\"><font style=\"color:#e67e22\" size=\"4\"></label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\"> Close \r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"submit\" onclick=\"javascript:FormSubmit();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form name=deleteTimeSlot action=\"ts-manage\" method=\"post\" onsubmit=\"return false;\">\r\n");
      out.write("\t<div class=\"modal fade\" id=\"deleteTimeSlotModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"deleteTimeSlotTitle\">Delete Time Slot</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"StartTime\">Start Time:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"time\" class=\"form-control\" name=StartTime2 id=\"StartTime2\" step=\"300\">\r\n");
      out.write("\t\t \t\t\t\t<label for=\"EndTime\">End Time:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"time\" class=\"form-control\" name=EndTime2 id=\"EndTime2\" step=\"300\">\r\n");
      out.write("\t\t \t\t\t\t<label for=\"Date\">Date:</label>\r\n");
      out.write("\t\t \t\t\t\t<input type=\"date\" class=\"form-control\" name=Date id=\"Date\">\r\n");
      out.write("\t\t \t\t\t\t<input type=\"hidden\" name=pname id=\"pname\">\r\n");
      out.write("\t\t \t\t\t\t<label id=\"result2\"><font style=\"color:#e67e22\" size=\"4\"></label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\"> Close \r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"submit\" onclick=\"javascript:validate();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script> function FormSubmit(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar starttime = document.getElementById(\"starttime\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar endtime = document.getElementById(\"endtime\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar date = document.getElementById(\"opendate\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar repeat = document.getElementById(\"repeat\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar params = ('starttime='+starttime+'&endtime='+endtime+'&opendate='+date+'&repeat='+repeat);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (xmlhttp.readyState==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"result\").innerHTML = xmlhttp.responseText;\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.open(\"POST\",\"availability\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-length\",params.length);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Connection\",\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.send(params);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.getElementById(\"result\").innerHTML = \"Attempting to add time slot...\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction validate(){\r\n");
      out.write("\t\tvar valid = confirm('Are you sure you want to delete?');\t\r\n");
      out.write("\t\tif (valid == true){\r\n");
      out.write("\t\t\tvar starttime = document.getElementById(\"StartTime2\").value;\r\n");
      out.write("\t\t\tvar endtime = document.getElementById(\"EndTime2\").value;\r\n");
      out.write("\t\t\tvar date = document.getElementById(\"Date\").value;\r\n");
      out.write("\t\t\tvar pname = document.getElementById(\"pname\").value;\r\n");
      out.write("\t\t\tvar params = ('StartTime2='+starttime+'&EndTime2='+endtime+'&Date='+date+'&pname='+pname);\r\n");
      out.write("\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\txmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\tif (xmlhttp.readyState==4){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"result2\").innerHTML = xmlhttp.responseText;\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txmlhttp.open(\"POST\",\"ts-manage\",true);\r\n");
      out.write("\t\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\txmlhttp.setRequestHeader(\"Content-length\",params.length);\r\n");
      out.write("\t\t\txmlhttp.setRequestHeader(\"Connection\",\"close\");\r\n");
      out.write("\t\t\txmlhttp.send(params);\r\n");
      out.write("\t\t\tdocument.getElementById(\"result2\").innerHTML = \"Attempting to delete time slot...\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t#calendar{\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
