/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 18:02:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class create_005fadvisor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (String) request.getAttribute("includeHeader"), out, false);
      out.write("\r\n");
      out.write("\t<label><font color=\"#e67e22\" size=\"5\"> Create New Advisor: </label>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t<form action=\"create_advisor\" method=\"post\" name=\"advisor_form\" onsubmit=\"return false;\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"emailAddress\"><font color=\"#e67e22\" size=\"4\">Email Address</label><br>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" style=\"width:350px;\" class=\"form-control\" id=\"emailAddress\"\r\n");
      out.write("\t\t \t\t\t\tplaceholder=\"advisor@uta.edu\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"pname\"><font color=\"#e67e22\" size=\"4\">Display Name</label><br>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" style=\"width:350px;\"class=\"form-control\" id=\"pname\"\r\n");
      out.write("\t\t \t\t\t\tplaceholder=\"Dr. Advisor\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"submit\" onclick=\"javascript:FormSubmit();\">\r\n");
      out.write("\t</form>\t\t\t \t\r\n");
      out.write("\t<label id=\"result\"><font color=\"#e67e22\" size=\"4\"></font></label>\r\n");
      out.write("\t<script> function FormSubmit(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar email = document.getElementById(\"emailAddress\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar pname = document.getElementById(\"pname\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar params = ('emailAddress='+email+'&pname='+pname);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (xmlhttp.readyState==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"result\").innerHTML = xmlhttp.responseText;\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.open(\"POST\",\"create_advisor\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-length\",params.length);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Connection\",\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.send(params);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.getElementById(\"result\").innerHTML = \"Attempting to create new Advisor...\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
