/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 17:40:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/top_header.jsp", Long.valueOf(1445168468285L));
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/header.jsp", Long.valueOf(1418330810000L));
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MavAppoint</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"description\" content=\"Full view calendar component for twitter bootstrap with year, month, week, day views.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"jQuery,Bootstrap,Calendar,HTML,CSS,JavaScript,responsive,month,week,year,day\">\r\n");
      out.write("\t<meta http-equiv=\"CACHE-CONTROL\" content=\"NO-CACHE\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.modal.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/underscore/underscore-min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jstimezonedetect/jstz.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/lib/moment.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/fullcalendar.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\tbody {padding-top:100px;padding-bottom:100px;background:url(img/engineering.jpg);background-size:cover;background-repeat:no-repeat;}\r\n");
      out.write("\t.brand\r\n");
      out.write("\t{\r\n");
      out.write("\t  background:url(img/mavlogo.gif) no-repeat left center;\r\n");
      out.write("\t  height:20px;\r\n");
      out.write("\t  width:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t<div id=\"inversenavbar\" class=\"container-fluid\" style=\"background-color:#104E8B;\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\t\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index\"> <b> <font style=\"color:#e67e22\" size=\"6\"> MavAppoint </font></b></a>\r\n");
      out.write("\t\t\t</div>");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"advising\"><font style=\"color:#e67e22\">Advising</font> </a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li><a href=\"register\"><span class=\"glyphicon glyphicon-user\"><font style=\"color:#e67e22\">Register</font></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"><font style=\"color:#e67e22\">Login</font></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".panel-heading {\r\n");
      out.write("    padding: 5px 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel-footer {\r\n");
      out.write("\tpadding: 1px 15px;\r\n");
      out.write("\tcolor: #A0A0A0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-img {\r\n");
      out.write("\twidth: 96px;\r\n");
      out.write("\theight: 96px;\r\n");
      out.write("\tmargin: 0 auto 10px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\t-moz-border-radius: 50%;\r\n");
      out.write("\t-webkit-border-radius: 50%;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container\" style=\"margin-top:40px\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<strong> Sign in to continue</strong>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form role=\"form\" action=\"#\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img class=\"profile-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"img/mavblue.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12 col-md-10  col-md-offset-1 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=emailAddress placeholder=\"yourname@mavs.uta.edu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=password>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-lg btn-primary btn-block\" value=\"Sign in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-footer \">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
