/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 17:40:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/top_header.jsp", Long.valueOf(1445168468285L));
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/header.jsp", Long.valueOf(1418330810000L));
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MavAppoint</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"description\" content=\"Full view calendar component for twitter bootstrap with year, month, week, day views.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"jQuery,Bootstrap,Calendar,HTML,CSS,JavaScript,responsive,month,week,year,day\">\r\n");
      out.write("\t<meta http-equiv=\"CACHE-CONTROL\" content=\"NO-CACHE\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.modal.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/underscore/underscore-min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jstimezonedetect/jstz.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/lib/moment.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/fullcalendar.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\tbody {padding-top:100px;padding-bottom:100px;background:url(img/engineering.jpg);background-size:cover;background-repeat:no-repeat;}\r\n");
      out.write("\t.brand\r\n");
      out.write("\t{\r\n");
      out.write("\t  background:url(img/mavlogo.gif) no-repeat left center;\r\n");
      out.write("\t  height:20px;\r\n");
      out.write("\t  width:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t<div id=\"inversenavbar\" class=\"container-fluid\" style=\"background-color:#104E8B;\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\t\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index\"> <b> <font style=\"color:#e67e22\" size=\"6\"> MavAppoint </font></b></a>\r\n");
      out.write("\t\t\t</div>");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"advising\"><font style=\"color:#e67e22\">Advising</font> </a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li><a href=\"register\"><span class=\"glyphicon glyphicon-user\"><font style=\"color:#e67e22\">Register</font></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"><font style=\"color:#e67e22\">Login</font></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("var ieDOM = false, nsDOM = false;\r\n");
      out.write("var stdDOM = document.getElementById; function initMethod()\r\n");
      out.write("{\r\n");
      out.write("//Determine the browser support for the DOM\r\n");
      out.write("if( !stdDOM )\r\n");
      out.write("{\r\n");
      out.write("ieDOM = document.all;\r\n");
      out.write("\r\n");
      out.write("if( !ieDOM )\r\n");
      out.write("{\r\n");
      out.write("nsDOM = ((navigator.appName.indexOf('Netscape') != -1) && (parseInt(navigator.appVersion) ==4));\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("passwordChanged();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getObject(objectId)\r\n");
      out.write("{\r\n");
      out.write("if (stdDOM) return document.getElementById(objectId);\r\n");
      out.write("if (ieDOM) return document.all[objectId];\r\n");
      out.write("if (nsDOM) return document.layers[objectId];\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getObjectStyle(objectId)\r\n");
      out.write("{\r\n");
      out.write("if (nsDOM) return getObject(objectId);\r\n");
      out.write("\r\n");
      out.write("var obj = getObject(objectId);\r\n");
      out.write("return obj.style;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showDefault(objectId)\r\n");
      out.write("{\r\n");
      out.write("showCell(objectId, \"#E2E2E2\", \"#E2E2E2\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showCell(objectId, foreColor, backColor)\r\n");
      out.write("{\r\n");
      out.write("getObjectStyle(objectId).color = foreColor;\r\n");
      out.write("getObjectStyle(objectId).backgroundColor = backColor;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showWeak()\r\n");
      out.write("{\r\n");
      out.write("showCell(\"pwWeak\", \"Black\", \"#FF6666\");\r\n");
      out.write("\r\n");
      out.write("showDefault(\"pwMedium\");\r\n");
      out.write("showDefault(\"pwStrong\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showMedium()\r\n");
      out.write("{\r\n");
      out.write("showCell(\"pwWeak\", \"#FFCC66\", \"#FFCC66\");\r\n");
      out.write("showCell(\"pwMedium\", \"Black\", \"#FFCC66\");\r\n");
      out.write("\r\n");
      out.write("showDefault(\"pwStrong\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showStrong()\r\n");
      out.write("{\r\n");
      out.write("showCell(\"pwWeak\", \"#80FF80\", \"#80FF80\");\r\n");
      out.write("showCell(\"pwMedium\", \"#80FF80\", \"#80FF80\");\r\n");
      out.write("showCell(\"pwStrong\", \"Black\", \"#80FF80\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showUndetermined()\r\n");
      out.write("{\r\n");
      out.write("showDefault(\"pwWeak\");\r\n");
      out.write("showDefault(\"pwMedium\");\r\n");
      out.write("showDefault(\"pwStrong\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function passwordChanged()\r\n");
      out.write("{\r\n");
      out.write("var strongRegex = new RegExp(\"^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\\\\W).*$\", \"g\");\r\n");
      out.write("var mediumRegex = new RegExp(\"^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$\", \"g\");\r\n");
      out.write("var enoughRegex = new RegExp(\"(?=.{6,}).*\", \"g\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var pwd = getObject(\"password\").value;\r\n");
      out.write("if( false == enoughRegex.test(pwd) )\r\n");
      out.write("{\r\n");
      out.write("showUndetermined();\r\n");
      out.write("}\r\n");
      out.write("else if( strongRegex.test(pwd) )\r\n");
      out.write("{\r\n");
      out.write("showStrong();\r\n");
      out.write("}\r\n");
      out.write("else if( mediumRegex.test( pwd ) )\r\n");
      out.write("{\r\n");
      out.write("showMedium();\r\n");
      out.write("}\r\n");
      out.write("else\r\n");
      out.write("{\r\n");
      out.write("showWeak();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateConfirmPassword(){\r\n");
      out.write("if(validate_required((password.value != repeatPassword.value),\"Your password and confirmation password do not match.\")==false) {\r\n");
      out.write("repeatPassword.focus();return false;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-4 col-lg-4\">\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"userid\">User ID</label>\r\n");
      out.write("\t\t\t <input type=\"text\" class=\"form-control\" id=userid\r\n");
      out.write("\t\t\t placeholder=\"1000xxxxxx or 6000xxxxxx\" name=\"userid\" required=\"required\">\r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t <label for=\"emailAddress\">Email Address</label>\r\n");
      out.write("\t\t\t <input type=\"email\" class=\"form-control\" id=emailAddress name=\"emailAddress\"\r\n");
      out.write("\t\t\t placeholder=\"firstname.lastname@mavs.uta.edu\" required=\"required\">\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t <label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t <input type=\"password\" class=\"form-control\" id=password name=\"password\" onkeyup=\"return passwordChanged();\" required=\"required\">\r\n");
      out.write("\t\t\t  <TABLE style=\"BORDER-RIGHT: black thin solid; BORDER-TOP: black thin solid; FONT-SIZE: 75%; BORDER-LEFT: black thin solid; BORDER-BOTTOM: black thin solid\"\r\n");
      out.write("\r\n");
      out.write("cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\">\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("\r\n");
      out.write("<TD id=\"pwWeak\" style=\"BORDER-RIGHT: black thin solid\" align=\"center\" width=\"34%\" title=\"Has at least six characters\">Weak</TD>\r\n");
      out.write("\r\n");
      out.write("<TD id=\"pwMedium\" style=\"BORDER-RIGHT: black thin solid\" align=\"center\" width=\"33%\" title=\"Has a mix of numbers, lower & upper case characters.\">Medium</TD>\r\n");
      out.write("\r\n");
      out.write("<TD id=\"pwStrong\" align=\"center\" width=\"33%\" title=\"Has numbers, special characters, lower & upper case characters.\">Strong</TD>\r\n");
      out.write("\r\n");
      out.write("</TR>\r\n");
      out.write("\r\n");
      out.write("</TABLE>\r\n");
      out.write("\t\t\t <label for=\"repeatPassword\">Repeat Password</label>\r\n");
      out.write("\t\t\t <input type=\"password\" class=\"form-control\" id=repeatPassword required=\"required\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<button type=\"submit\" class=\"btn btn-primary\" >Submit</button></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\t\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
