/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 17:59:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import uta.mav.appoint.login.LoginUser;
import uta.mav.appoint.login.AdminUser;
import uta.mav.appoint.login.AdvisorUser;
import uta.mav.appoint.login.StudentUser;
import uta.mav.appoint.login.FacultyUser;
import uta.mav.appoint.beans.AppointmentType;
import java.util.ArrayList;
import uta.mav.appoint.TimeSlotComponent;
import uta.mav.appoint.PrimitiveTimeSlot;
import uta.mav.appoint.CompositeTimeSlot;

public final class schedule_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (String) request.getAttribute("includeHeader"), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
 LoginUser user = (LoginUser)session.getAttribute("user"); 
      out.write("\r\n");
      out.write("\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 ArrayList<AppointmentType> ats = (ArrayList<AppointmentType>)session.getAttribute("appointmenttypes");
		if (ats != null){
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-default btn-lg dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\tSelect Advising Type for ");
      out.print(request.getParameter("pname"));
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t");
for (int i=0;i<ats.size();i++){
				
      out.write("<li><a href=\"?apptype=");
      out.print(ats.get(i).getType());
      out.write("&pname=");
      out.print(request.getParameter("pname"));
      out.write("&advisor_email=");
      out.print(ats.get(0).getEmail());
      out.write("&id1=");
      out.print(request.getParameter("id1"));
      out.write("&duration=");
      out.print(ats.get(i).getDuration());
      out.write('"');
      out.write('>');
      out.print(ats.get(i).getType());
      out.write("</a></li> ");

			}
		}
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br><hr>\r\n");
      out.write("\t\t<div id='calendar'></div>\r\n");
      out.write("   \t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 TimeSlotComponent schedule = (TimeSlotComponent)session.getAttribute("timeslot");
		    			if (schedule != null){
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t<script>\r\n");
      out.write("\t\t    \t\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t    \t\t\t\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t    \t\t\t\t\t\tdefaultView : 'basicDay',\r\n");
      out.write("\t\t    \t\t\t\t\t\tviewRender: function(view, element){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t$('#calendar').fullCalendar('gotoDate','");
      out.print(schedule.getDate());
      out.write("');\r\n");
      out.write("\t\t    \t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\t\tdisplayEventEnd : {\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tmonth: false,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tbasicWeek: false,\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t'default' : false,\r\n");
      out.write("\t\t    \t\t\t\t\t\t}");
if(request.getParameter("duration") != null){
      out.write(",\r\n");
      out.write("\t\t    \t\t\t\t\t\teventClick: function(event,element){\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"id2\").value = event.id;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"apptype\").value = '");
      out.print(request.getParameter("apptype"));
      out.write("';\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"duration\").value = '");
      out.print(request.getParameter("duration"));
      out.write("';\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"pname\").value = '");
      out.print(request.getParameter("pname"));
      out.write("';\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"advisor_email\").value = '");
      out.print(request.getParameter("advisor_email"));
      out.write("';\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"start\").value = event.start;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"end\").value = event.end;\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"starttime\").value = event.start.format();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\tdocument.getElementById(\"endtime\").value = event.end.format();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t$('#addApptModal').modal();\r\n");
      out.write("\t\t    \t\t\t\t\t\t\t},\r\n");
      out.write("\t\t    \t\t\t\t\tevents: [\r\n");
      out.write("\t\t    \t\t\t\t\t    ");
      out.print(schedule.getEvent(Integer.parseInt(request.getParameter("duration"))/5));
      out.write("     \r\n");
      out.write("\t\t    \t\t\t\t\t        ]");
}
      out.write("\t\r\n");
      out.write("\t\t    \t\t\t\t\t});\r\n");
      out.write("\t\t    \t\t\t\t});\r\n");
      out.write("\t \t\t\t\t\t\t</script>\t\r\n");
      out.write("\t\t \t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t<br/><br/><hr>\r\n");
      out.write("\t<form name=addAppt action=\"schedule\" method=\"post\">\r\n");
      out.write("\t<div class=\"modal fade\" id=\"addApptModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=addApptTypeLabel\">Add Appointment</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=id2 id=\"id2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=apptype id=\"apptype\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=start id=\"start\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=end id=\"end\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=starttime id=\"starttime\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=endtime id=\"endtime\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=pname id=\"pname\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=duration id=\"duration\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=advisor_email id=\"advisor_email\">\r\n");
      out.write("\t\t\t\t\t\tEmail address: <br><input type=\"text\" name=\"email\" id=\"email\" value=\"");
      out.print( user.getEmail());
      out.write("\"><br>\r\n");
      out.write("\t\t\t\t\t\tUTA Student ID: <br><input type=\"text\" name=\"studentid\"> <br>\r\n");
      out.write("\t\t\t\t\t\tDescription: <br><textarea rows=4 columns=\"10\" name=\"description\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\"> Close \r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\" onclick=\"javascript:FormSubmit();\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("<style>\r\n");
      out.write("\t#calendar{\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\t\r\n");
      out.write("<script> function FormSubmit(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar student_email = document.getElementById(\"email\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar advisor_email = document.getElementById(\"advisor_email\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar starttime = document.getElementById(\"starttime\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar endtime = document.getElementById(\"endtime\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar params = ('student_email='+student_email+'&advisor_email='+advisor_email+'&starttime='+starttime+'&endtime='+endtime);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.open(\"POST\",\"mail\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-length\",params.length);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Connection\",\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.send(params);\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"Meeting request sent.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
