/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 17:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import uta.mav.appoint.beans.Appointment;

public final class view_005fappointments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/footer.jsp", Long.valueOf(1417683026000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (String) request.getAttribute("includeHeader"), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<style>\r\n");
      out.write(".custab{\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    margin: 5% 0;\r\n");
      out.write("    box-shadow: 3px 3px 2px #ccc;\r\n");
      out.write("    transition: 0.5s;\r\n");
      out.write("    background-color:#e67e22;\r\n");
      out.write("    }\r\n");
      out.write(".custab:hover{\r\n");
      out.write("    box-shadow: 3px 3px 0px transparent;\r\n");
      out.write("    transition: 0.5s;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"btn-group\">\r\n");
      out.write("\t<form action=\"appointments\" method=\"post\" name=\"cancel\">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=hidden name=cancel_button id=\"cancel_button\">\r\n");
      out.write("    <input type=hidden name=edit_button id=\"edit_button\">\r\n");
      out.write("    <div class=\"row col-md-16  custyle\">\r\n");
      out.write("    <table class=\"table table-striped custab\">\r\n");
      out.write("    <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>Advisor Name</th>\r\n");
      out.write("            <th>Appointment Date</th>\r\n");
      out.write("\t\t\t<th>Start Time</th>\r\n");
      out.write("\t\t\t<th>End Time</th>\r\n");
      out.write("\t\t\t<th>Advising Type</th>\r\n");
      out.write("\t\t\t<th>Advising Email</th>\r\n");
      out.write("\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t<th>UTA Student ID</th>\r\n");
      out.write("            <th>Student Email</th>\r\n");
      out.write("            <th class=\"text-center\">Action</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("            \t\t\r\n");
      out.write("\t\t    \t\t\r\n");
      out.write("\t\t    \t\t<!-- begin processing appointments  -->\r\n");
      out.write("\t\t    \t\t");
 ArrayList<Appointment> array = (ArrayList<Appointment>)session.getAttribute("appointments");
		    			if (array != null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
for (int i=0;i<array.size();i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                \t\t\t\t<td>");
      out.print(array.get(i).getPname());
      out.write("</td>\r\n");
      out.write("                \t\t\t\t<td>");
      out.print(array.get(i).getAdvisingDate());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getAdvisingStartTime());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getAdvisingEndTime());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getAppointmentType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getAdvisorEmail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getDescription() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getStudentid());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(array.get(i).getStudentEmail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><button type=\"button\" id=button1");
      out.print(i);
      out.write(" onclick=\"button");
      out.print(i);
      out.write("()\">Cancel</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><button type=\"button\" id=button2_");
      out.print(i);
      out.write(" onclick=\"button_");
      out.print(i);
      out.write("()\">Edit</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"text-center\"><button type=\"button\" id=button3_");
      out.print(i);
      out.write(" onclick=\"button__");
      out.print(i);
      out.write("()\">Email</button></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script> function button");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"cancel_button\").value = \"");
      out.print(array.get(i).getAppointmentId());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (validate() == true){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcancel.submit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script> function button_");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"id2\").value = \"");
      out.print(array.get(i).getAppointmentId());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"apptype\").value = \"");
      out.print(array.get(i).getAppointmentType());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"date\").value = \"");
      out.print(array.get(i).getAdvisingDate());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"start\").value = \"");
      out.print(array.get(i).getAdvisingStartTime());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"end\").value = \"");
      out.print(array.get(i).getAdvisingEndTime());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"pname\").value = \"");
      out.print(array.get(i).getPname());
      out.write("\"; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"description\").value = \"");
      out.print(array.get(i).getDescription());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#addApptModal').modal();\r\n");
      out.write("\t\t\t\t\t\t\t\t}</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script> function button__");
      out.print(i);
      out.write("(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById(\"to\").value = \"");
      out.print(array.get(i).getStudentEmail());
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#emailModal').modal();\r\n");
      out.write("\t\t\t\t\t\t\t\t}</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script> function emailSend(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar to = document.getElementById(\"to\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar body = document.getElementById(\"email\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar subject = document.getElementById(\"subject\").value;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar params = ('to='+to+'&body='+body+'&subject='+subject);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar xmlhttp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (xmlhttp.readyState==4){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\talert(\"Email sent.\");\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.open(\"POST\",\"notify\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-type\",\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Content-length\",params.length);\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.setRequestHeader(\"Connection\",\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\txmlhttp.send(params);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");
	}
		    			}
		    			
      out.write(" \r\n");
      out.write("\t\t\t\t\t <!-- end processing advisors -->\t \r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<form name=addAppt action=\"manage\" onsubmit=\"return validate2()\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"modal fade\" id=\"addApptModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=addApptTypeLabel\">Update Appointment</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=id2 id=\"id2\" readonly>\r\n");
      out.write("\t\t\t\t\t\t<b>Type:</b><input type=\"label\" name=apptype id=\"apptype\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>Date:    </b><input type=\"text\" id=\"date\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>Start:   </b><input type=\"label\" name=start id=\"start\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>End:     </b><input type=\"label\" name=end id=\"end\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>Advisor: </b><input type=\"label\" name=pname id=\"pname\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>UTA Student ID: </b><br><input type=\"text\" name=studentid id=\"studentid\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>Description:</b><br><textarea rows=4 columns=\"10\" name=description id=\"description\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\"> Close \r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("<form name=emailSubmit onsubmit=\"return emailSend()\">\r\n");
      out.write("<div class=\"modal fade\" id=\"emailModal\" tabindex=\"-1\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\">Send message</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t<b>Subject:</b><br><input type=text name=subject id=\"subject\"><br>\r\n");
      out.write("\t\t\t\t\t\t<b>Message:</b><br><textarea rows=4 columns=\"10\" name=email id=\"email\"></textarea><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=hidden name=to id=\"to\"><br>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\"> Close \r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("<script>\r\n");
      out.write("function validate(){\r\n");
      out.write("\t\treturn confirm('Are you sure you want to delete this appointment?');\t\r\n");
      out.write("\t}\r\n");
      out.write("function validate2(){\r\n");
      out.write("\t\tif (document.getElementById(\"studentid\").value == \"\"){\r\n");
      out.write("\t\t\talert(\"Student ID is required.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (document.getElementById(\"description\").value.length > 100){\r\n");
      out.write("\t\t\talert(\"Description is too long, please shorten it.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
