/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-10-19 18:03:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class advisor_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/views/templates/top_header.jsp", Long.valueOf(1445168468285L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>MavAppoint</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta name=\"description\" content=\"Full view calendar component for twitter bootstrap with year, month, week, day views.\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"jQuery,Bootstrap,Calendar,HTML,CSS,JavaScript,responsive,month,week,year,day\">\r\n");
      out.write("\t<meta http-equiv=\"CACHE-CONTROL\" content=\"NO-CACHE\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"components/bootstrap3/css/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/fullcalendar.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jquery/jquery.modal.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/underscore/underscore-min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/jstimezonedetect/jstz.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/lib/moment.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/fullcalendar.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"components/bootstrap3/js/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\tbody {padding-top:100px;padding-bottom:100px;background:url(img/engineering.jpg);background-size:cover;background-repeat:no-repeat;}\r\n");
      out.write("\t.brand\r\n");
      out.write("\t{\r\n");
      out.write("\t  background:url(img/mavlogo.gif) no-repeat left center;\r\n");
      out.write("\t  height:20px;\r\n");
      out.write("\t  width:20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t<div id=\"inversenavbar\" class=\"container-fluid\" style=\"background-color:#104E8B;\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\t\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"index\"> <b> <font style=\"color:#e67e22\" size=\"6\"> MavAppoint </font></b></a>\r\n");
      out.write("\t\t\t</div>");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"availability\"><font style=\"color:#e67e22\"> Update Schedule</font> </a></li>\n");
      out.write("\t\t\t\t<li><a href=\"appointments\"><font style=\"color:#e67e22\"> Appointments</font> </a></li>\n");
      out.write("\t\t\t\t<li><a href=\"advising\"><font style=\"color:#e67e22\"> Show Schedule </font></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"customize\"><font style=\"color:#e67e22\">Customize Settings</font></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li><a href=\"#\"><font style=\"color:#e67e22\">You are logged in as an Advisor.</font></a></li>\n");
      out.write("\t\t\t\t<li><a href=\"logout\"><span class=\"glyphicon glyphicon-log-in\"><font style=\"color:#e67e22\">Logout</font></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
